security:
  oauth2:
    client:
       clientId: 55237be5d2662f50cc7b
       clientSecret: 5f2516582d80f74b677ed66554fc61f77e4cae35
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false 